// <auto-generated />
namespace ShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Productclassadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Productclassadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201809081337008_Product class added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
